name: metalservicemarkazi

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${NUXT_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NUXT_PORT=${NUXT_PORT}
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    # image: strapi:latest    
    restart: unless-stopped
    # user: "${STRAPI_UID:-1000}:${STRAPI_GID:-1000}"
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${STRAPI_PORT}:${STRAPI_PORT}"
    # volumes:
      # - ./backend/config:/opt/app/config
      # - ./backend/src:/opt/app/src
      # - ./backend/package.json:/opt/package.json
      # - ./.env:/opt/app/.env
      # - ./backend/public/uploads:/opt/app/public/uploads
    networks:
      - strapi-network
    depends_on:
      - strapiDB

  strapiDB:
    platform: linux/arm64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapiDB-data:/var/lib/postgresql/data/
    networks:
      - strapi-network

volumes:
  strapiDB-data:

networks:
  strapi-network:
